#!/bin/sh

colbg='#191724'
colfg='#e0def4'
col1='#eb6f92'
col2='#f6c177'
col3='#c4a7e7'
col4='#9ccfd8'

function update {
    total_mem=$(free -h | grep "Mem:" | awk '{ print $2 }')
    used_mem=$(free -h | grep "Mem:" | awk '{ print $3 }')
    mem="󰍛 $used_mem/$total_mem"

    total_root=$(df -h / | grep "/dev/" | awk '{ print $2 }')
    used_root=$(df -h / | grep "/dev/" | awk '{ print $3 }')
    root="󱛟 $used_root/$total_root"

    total_home=$(df -h /home | grep "/dev/" | awk '{ print $2 }')
    used_home=$(df -h /home | grep "/dev/" | awk '{ print $3 }')
    home="󱂵 $used_home/$total_home"

    time="󱑂 $(date '+%I:%M:%S %p')"

    date="󰃭 $(date '+%a, %b %d')"

    status="  $mem | $root | $date | $time  "
    xsetroot -name "$status"
}

while true
do
    update
    sleep 5
done
